##-- cdb Cargo.toml file --##
# note: do not change the mark above #

[workspace]

members = [
    "cdb_rs",
    "cdbgen",
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = true
opt-level = 0

[term]
verbose = true
