[workspace]

members = [
    "cdb_rs",
    "cdb_ffi",
    "cdb_ccommon",
    "cdbgen",
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = true
opt-level = 0
codegen-units = 4

[term]
verbose = true
